# Generated by Django 4.2.16 on 2024-11-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customeruser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replenishmentbalance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed')], default='pending', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
